### gateway 测试
POST {{gateway_host}}/content/course/list?pageNo=2&pageSize=1
Content-Type: application/json

{
  "auditStatus": "202002",
  "courseName": ""
}

### 上传文件
POST {{media_host}}/media/upload/coursefile
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="屏幕截图_20221021_151708.png"
Content-Type: application/octet-stream

< C:/Users/Hao Ge/OneDrive/图片/屏幕快照/屏幕截图_20221021_151708.png



